extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Material_0_f3d_lights;
extern Lights1 bob_dl_Material_1_f3d_lights;
extern Lights1 bob_dl_Material_2_f3d_lights;
extern Lights1 bob_dl_Material_3_f3d_lights;
extern Lights1 bob_dl_Material_4_f3d_lights;
extern Lights1 bob_dl_Material_5_f3d_lights;
extern Lights1 bob_dl_Material_6_f3d_lights;
extern u8 bob_dl__0_rgba16[];
extern u8 bob_dl__1_rgba16[];
extern u8 bob_dl__2_rgba16[];
extern u8 bob_dl__3_rgba16[];
extern u8 bob_dl__4_rgba16[];
extern u8 bob_dl__5_rgba16[];
extern u8 bob_dl__6_rgba16[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_node_mesh_layer_1_vtx_0[1632];
extern Gfx bob_dl_node_mesh_layer_1_tri_0[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_1[340];
extern Gfx bob_dl_node_mesh_layer_1_tri_1[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_2[488];
extern Gfx bob_dl_node_mesh_layer_1_tri_2[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_3[294];
extern Gfx bob_dl_node_mesh_layer_1_tri_3[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_4[253];
extern Gfx bob_dl_node_mesh_layer_1_tri_4[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_5[565];
extern Gfx bob_dl_node_mesh_layer_1_tri_5[];
extern Vtx bob_dl_node_mesh_layer_1_vtx_6[41];
extern Gfx bob_dl_node_mesh_layer_1_tri_6[];
extern Gfx mat_bob_dl_Material_0_f3d[];
extern Gfx mat_bob_dl_Material_1_f3d[];
extern Gfx mat_bob_dl_Material_2_f3d[];
extern Gfx mat_bob_dl_Material_3_f3d[];
extern Gfx mat_bob_dl_Material_4_f3d[];
extern Gfx mat_bob_dl_Material_5_f3d[];
extern Gfx mat_bob_dl_Material_6_f3d[];
extern Gfx bob_dl_node_mesh_layer_1[];
